const getAssetUrl = (path: string): string => {
  return new URL(`../assets/icons/${path}`, import.meta.url).href;
};

export const technicalSkills: { category: string; items: { name: string; img?: string }[] }[] = [
  {
    category: 'Programming languages',
    items: [
      { name: 'Python', img: getAssetUrl('python-light.svg') },
      { name: 'C#', img: getAssetUrl('c-light.svg') },
      { name: 'SQL', img: getAssetUrl('sql-light.svg') },
      { name: 'PL/SQL', img: getAssetUrl('oracle-light.svg') },
      { name: 'VB.NET', img: getAssetUrl('vbnet-light.svg') },
      { name: 'VB6', img: getAssetUrl('vb6-light.svg') },
      { name: 'VB Script', img: getAssetUrl('vbscript-light.svg') },
      { name: 'JavaScript', img: getAssetUrl('js-light.svg') },
      { name: 'CSS', img: getAssetUrl('css-light.svg') },
      { name: 'HTML', img: getAssetUrl('html-light.svg') },
    ],
  },
  {
    category: 'Technologies',
    items: [
      { name: 'Reflex', img: getAssetUrl('reflex-light.svg') },
      { name: 'Tkinter', img: getAssetUrl('tk-light.svg') },
      { name: '.NET Core', img: getAssetUrl('dotnetcore-light.svg') },
      { name: 'WPF', img: getAssetUrl('wpf-light.svg') },
      { name: 'gRPC', img: getAssetUrl('grpc-light.svg') },
      { name: 'Web API', img: getAssetUrl('webapi-light.svg') },
      { name: 'WinForms', img: getAssetUrl('winforms-light.svg') },
      { name: 'ASP.NET', img: getAssetUrl('aspnet-light.svg') },
      { name: 'WCF/Windows Services', img: getAssetUrl('wcf-light.svg') },
      { name: 'ADO.NET', img: getAssetUrl('adonet-light.svg') },
      { name: 'LINQ', img: getAssetUrl('linq-light.svg') },
      { name: 'Blazor', img: getAssetUrl('blazor-light.svg') },
      { name: 'ASP.NET Web Services', img: getAssetUrl('aspnetwebservices-light.svg') },
      { name: 'ASP', img: getAssetUrl('asp-light.svg') },
      { name: 'IBM and MS MQ', img: getAssetUrl('ibm-light.svg') },
      { name: 'ASP.NET Core', img: getAssetUrl('aspnetcore-light.svg') },
      { name: 'REST API', img: getAssetUrl('restapi-light.svg') },
      { name: 'React', img: getAssetUrl('react-light.svg') },
      { name: 'Infragistics Controls', img: getAssetUrl('infragistics-light.svg') },
      { name: 'Tableau', img: getAssetUrl('tableau-light.svg') },
      { name: 'Crystal Reports', img: getAssetUrl('crystal-light.svg') },
      { name: 'SSRS Reports', img: getAssetUrl('ssrs-light.svg') },
      { name: 'SOAP', img: getAssetUrl('soap-light.svg') },
      { name: 'JSON', img: getAssetUrl('json-light.svg') },
      { name: 'XML', img: getAssetUrl('xml-light.svg') },
      { name: 'MSTest', img: getAssetUrl('mstest-light.svg') },
      { name: 'DataDog', img: getAssetUrl('datadog-light.svg') },
    ],
  },
  {
    category: 'Databases',
    items: [
      { name: 'SQL Server', img: getAssetUrl('sqlserver-light.svg') },
      { name: 'Oracle', img: getAssetUrl('oracle-light.svg') },
      { name: 'Sybase', img: getAssetUrl('sybase-light.svg') },
      { name: 'InterSystems Cache', img: getAssetUrl('cache-light.svg') },
      { name: 'MS Access', img: getAssetUrl('access-light.svg') },
    ],
  },
  {
    category: 'AI Assisted Tools',
    items: [
      { name: 'Cursor', img: getAssetUrl('cursor-light.svg') },
      { name: 'GitHub Copilot', img: getAssetUrl('github-light.svg') },
      { name: 'Lovable', img: getAssetUrl('love-light.svg') },
      { name: 'Bolt', img: getAssetUrl('bolt-light.svg') },
    ],
  },
  {
    category: 'Development Tools',
    items: [
      { name: 'PyCharm', img: 'https://cdn.worldvectorlogo.com/logos/pycharm.svg' },
      { name: 'MS Visual Studio', img: 'https://cdn.worldvectorlogo.com/logos/visual-studio-2013.svg' },
      { name: 'VS Code', img: 'https://cdn.worldvectorlogo.com/logos/visual-studio-code-1.svg' },
      { name: 'SQL Server Management Studio', img: 'https://cdn.worldvectorlogo.com/logos/microsoft-sql-server.svg' },
      { name: 'Rapid SQL', img: 'https://cdn.worldvectorlogo.com/logos/mysql-6.svg' },
      { name: 'Toad for Oracle', img: 'https://cdn.worldvectorlogo.com/logos/oracle-6.svg' },
      { name: 'MS Visio', img: 'https://cdn.worldvectorlogo.com/logos/microsoft-visio.svg' },
      { name: 'IIS', img: 'https://cdn.worldvectorlogo.com/logos/iis.svg' },
      { name: 'SMTP', img: 'https://cdn.worldvectorlogo.com/logos/mail.svg' },
    ],
  },
  {
    category: 'CI/CD Software',
    items: [
      { name: 'Azure DevOps', img: 'https://cdn.worldvectorlogo.com/logos/azure-1.svg' },
      { name: 'TeamCity', img: 'https://cdn.worldvectorlogo.com/logos/teamcity.svg' },
      { name: 'Git', img: 'https://cdn.worldvectorlogo.com/logos/git-icon.svg' },
      { name: 'BitBucket', img: 'https://cdn.worldvectorlogo.com/logos/bitbucket.svg' },
      { name: 'Jira', img: 'https://cdn.worldvectorlogo.com/logos/jira-1.svg' },
      { name: 'Confluence', img: 'https://cdn.worldvectorlogo.com/logos/confluence-1.svg' },
      { name: 'Jenkins', img: 'https://cdn.worldvectorlogo.com/logos/jenkins-1.svg' },
      { name: 'Nexus', img: 'https://cdn.worldvectorlogo.com/logos/sonatype.svg' },
      { name: 'UrbanCode Deploy', img: 'https://cdn.worldvectorlogo.com/logos/ibm.svg' },
      { name: 'SonarQube', img: 'https://cdn.worldvectorlogo.com/logos/sonarqube.svg' },
      { name: 'TFS', img: 'https://cdn.worldvectorlogo.com/logos/azure-devops.svg' },
    ],
  },
  {
    category: 'Methodology/Architecture',
    items: [
      { name: 'Agile' },
      { name: 'Scrum' },
      { name: 'Waterfall' },
      { name: 'Microservices' },
      { name: 'Plugins' },
      { name: 'MVVM' },
      { name: 'MVC' },
      { name: 'API' },
      { name: 'Dependency Injection' },
    ],
  },
  {
    category: 'APIs/Libraries',
    items: [
      { name: 'Charles River API/Plugins', img: 'https://cdn.worldvectorlogo.com/logos/api.svg' },
      { name: 'Fincad API', img: 'https://cdn.worldvectorlogo.com/logos/api.svg' },
      { name: 'MS Entity Framework', img: 'https://cdn.worldvectorlogo.com/logos/dot-net-core-7.svg' },
    ],
  },
  {
    category: 'Trading Systems',
    items: [
      { name: 'Charles River IMS', img: 'https://cdn.worldvectorlogo.com/logos/api.svg' },
      { name: 'HelioGraph', img: 'https://cdn.worldvectorlogo.com/logos/chart.svg' },
      { name: 'Omgeo Oasys/CTM', img: 'https://cdn.worldvectorlogo.com/logos/api.svg' },
    ],
  },
];
