const getAssetUrl = (path: string): string => {
  return new URL(`../assets/icons/${path}`, import.meta.url).href;
};

export const technicalSkills: { category: string; items: { name: string; img?: string }[] }[] = [
  {
    category: 'Programming languages',
    items: [
      { name: 'Python', img: getAssetUrl('python-light.svg') },
      { name: 'C#', img: getAssetUrl('c-light.svg') },
      { name: 'SQL', img: getAssetUrl('sql-light.svg') },
      { name: 'PL/SQL', img: getAssetUrl('oracle-light.svg') },
      { name: 'VB.NET', img: getAssetUrl('vbnet-light.svg') },
      { name: 'VB6', img: getAssetUrl('vb6-light.svg') },
      { name: 'VB Script', img: getAssetUrl('vbscript-light.svg') },
      { name: 'JavaScript', img: getAssetUrl('js-light.svg') },
      { name: 'CSS', img: getAssetUrl('css-light.svg') },
      { name: 'HTML', img: getAssetUrl('html-light.svg') },
    ],
  },
  {
    category: 'Technologies',
    items: [
      { name: 'Reflex', img: getAssetUrl('reflex-light.svg') },
      { name: 'Tkinter', img: getAssetUrl('tk-light.svg') },
      { name: '.NET Core', img: getAssetUrl('dotnetcore-light.svg') },
      { name: 'WPF', img: getAssetUrl('wpf-light.svg') },
      { name: 'gRPC', img: getAssetUrl('grpc-light.svg') },
      { name: 'Web API', img: getAssetUrl('webapi-light.svg') },
      { name: 'WinForms', img: getAssetUrl('winforms-light.svg') },
      { name: 'ASP.NET', img: getAssetUrl('aspnet-light.svg') },
      { name: 'WCF/Windows Services', img: getAssetUrl('wcf-light.svg') },
      { name: 'ADO.NET', img: getAssetUrl('adonet-light.svg') },
      { name: 'LINQ', img: getAssetUrl('linq-light.svg') },
      { name: 'Blazor', img: getAssetUrl('blazor-light.svg') },
      { name: 'ASP.NET Web Services', img: getAssetUrl('aspnetwebservices-light.svg') },
      { name: 'ASP', img: getAssetUrl('asp-light.svg') },
      { name: 'IBM and MS MQ', img: getAssetUrl('ibm-light.svg') },
      { name: 'ASP.NET Core', img: getAssetUrl('aspnetcore-light.svg') },
      { name: 'REST API', img: getAssetUrl('restapi-light.svg') },
      { name: 'React', img: getAssetUrl('react-light.svg') },
      { name: 'Infragistics Controls', img: getAssetUrl('infragistics-light.svg') },
      { name: 'Tableau', img: getAssetUrl('tableau-light.svg') },
      { name: 'Crystal Reports', img: getAssetUrl('crystal-light.svg') },
      { name: 'SSRS Reports', img: getAssetUrl('ssrs-light.svg') },
      { name: 'SOAP', img: getAssetUrl('soap-light.svg') },
      { name: 'JSON', img: getAssetUrl('json-light.svg') },
      { name: 'XML', img: getAssetUrl('xml-light.svg') },
      { name: 'MSTest', img: getAssetUrl('mstest-light.svg') },
      { name: 'DataDog', img: getAssetUrl('datadog-light.svg') },
    ],
  },
  {
    category: 'Databases',
    items: [
      { name: 'SQL Server', img: getAssetUrl('sqlserver-light.svg') },
      { name: 'Oracle', img: getAssetUrl('oracle-light.svg') },
      { name: 'Sybase', img: getAssetUrl('sybase-light.svg') },
      { name: 'InterSystems Cache', img: getAssetUrl('cache-light.svg') },
      { name: 'MS Access', img: getAssetUrl('access-light.svg') },
    ],
  },
  {
    category: 'AI Assisted Tools',
    items: [
      { name: 'Cursor', img: getAssetUrl('cursor-light.svg') },
      { name: 'GitHub Copilot', img: getAssetUrl('github-light.svg') },
      { name: 'Lovable', img: getAssetUrl('love-light.svg') },
      { name: 'Bolt', img: getAssetUrl('bolt-light.svg') },
      { name: 'Claude AI', img: getAssetUrl('claude-light.svg') },      
      { name: 'Meta AI', img: getAssetUrl('meta-light.svg') },      
      { name: 'Gemini', img: getAssetUrl('gemini-light.svg') },     
      { name: 'ChatGPT', img: getAssetUrl('chatgpt-light.svg') },     
      { name: 'Microsoft Copilot', img: getAssetUrl('mscopilot-light.svg') },     
    ],
  },
  {
    category: 'Development Tools',
    items: [
      { name: 'PyCharm', img: getAssetUrl('pycharm-light.svg') },   
      { name: 'MS Visual Studio', img: getAssetUrl('visualstudio-light.svg') },   
      { name: 'VS Code', img: getAssetUrl('vscode-light.svg') },   
      { name: 'SQL Server Management Studio', img: getAssetUrl('ssms-light.svg') },   
      { name: 'Rapid SQL', img: getAssetUrl('rapidsql-light.svg') },   
      { name: 'Toad for Oracle', img: getAssetUrl('toad-light.svg') },   
      { name: 'MS Visio', img: getAssetUrl('visio-light.svg') },   
      { name: 'IIS', img: getAssetUrl('iis-light.svg') },   
      { name: 'SMTP', img: getAssetUrl('smtp-light.svg') },   
    ],
  },
  {
    category: 'CI/CD Software',
    items: [
      { name: 'Azure DevOps', img: getAssetUrl('azure-light.svg') },  
      { name: 'TeamCity', img: getAssetUrl('teamcity-light.svg') },  
      { name: 'Git', img: getAssetUrl('git-light.svg') },  
      { name: 'BitBucket', img: getAssetUrl('bitbucket-light.svg') },  
      { name: 'Jira', img: getAssetUrl('jira-light.svg') },  
      { name: 'Confluence', img: getAssetUrl('confluence-light.svg') },  
      { name: 'Jenkins', img: getAssetUrl('jenkins-light.svg') },  
      { name: 'Nexus', img: getAssetUrl('nexus-light.svg') },  
      { name: 'UrbanCode Deploy', img: getAssetUrl('urban-light.svg') },  
      { name: 'SonarQube', img: getAssetUrl('sonarqube-light.svg') },  
      { name: 'TFS', img: getAssetUrl('tfs-light.svg') },  
    ],
  },
  {
    category: 'Methodology/Architecture',
    items: [
      { name: 'Agile', img: getAssetUrl('agile-light.svg') },  
      { name: 'Scrum', img: getAssetUrl('scrum-light.svg') },  
      { name: 'Waterfall', img: getAssetUrl('waterfall-light.svg') },  
      { name: 'Microservices', img: getAssetUrl('microservice-light.svg') },  
      { name: 'Plugins', img: getAssetUrl('plugin-light.svg') },  
      { name: 'MVVM', img: getAssetUrl('mvvm-light.svg') },  
      { name: 'MVC', img: getAssetUrl('mvc-light.svg') },  
      { name: 'API', img: getAssetUrl('api-light.svg') },  
      { name: 'Dependency Injection', img: getAssetUrl('injection-light.svg') },  
    ],
  },
  {
    category: 'APIs/Libraries',
    items: [
      { name: 'Charles River API/Plugins', img: getAssetUrl('crdplugin-light.svg') },  
      { name: 'Fincad API', img: getAssetUrl('fincadapi-light.svg') },  
      { name: 'MS Entity Framework', img: getAssetUrl('entityframework-light.svg') },  
    ],
  },
  {
    category: 'Trading Systems',
    items: [
      { name: 'Charles River IMS', img: getAssetUrl('crd-light.svg') },  
      { name: 'HelioGraph', img: getAssetUrl('helio-light.svg') },  
      { name: 'Omgeo Oasys/CTM', img: getAssetUrl('omgeo-light.svg') },  
    ],
  },
];
